### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by SeLLeRoNe** [kodi1/meteoalarm#1]
Hi there,
I would like to ask one thing and suggest another one.

Question: How does this differ from the HA integrated one? (https://www.home-assistant.io/integrations/meteoalarm/)

Suggestion: I would suggest to change the name, because it does conflict with the internal one, causing the internal one binary_sensor not to work anymore:
```
2020-01-16 12:08:52 ERROR (MainThread) [homeassistant.config] Platform error: binary_sensor
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 760, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 265, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.meteoalarm.binary_sensor'
```

Thanks :)
Andrea

**Comment by kodi1** [comment]
Official component rely on xml api, which is not reliable in some regions.
Renamed.

**Comment by SeLLeRoNe** [comment]
Thanks for the change and the explanation :)
