### ISSUE TITLE
Platform error sensor.meteoalarm_m - No module named 'bs4'

### ISSUE THREAD

**Issue by mfabiani53** [kodi1/meteoalarm#12]
Using the "Check Configuration" add-on i get this error:

"Platform error sensor.meteoalarm_m - No module named 'bs4'"

How to fix this?

**Comment by djgragra** [comment]
I have the same problem

**Comment by stefanolanfranco** [comment]
If needed my traceback:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config.py", line 872, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/meteoalarm_m/sensor.py", line 8, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by pilot1981** [comment]
Hi,
I have same error when I go to do check before update to 2021.10.1 version...any solution?

**Comment by kapiorr** [comment]
`python3 -m pip install bs4`

**Comment by caiosweet** [comment]
Simply add the module to the requirements list of the manifest.json file.

```
{
  "domain": "meteoalarm_m",
  "name": "meteoalarm_m",
  "documentation": "https://github.com/kodi1/meteoalarm",
  "dependencies": [],
  "codeowners": ["@kodi1"],
  "requirements": ["bs4==0.0.1"],
  "version": "0.0.1"
}
```

**Comment by pilot1981** [comment]
I already have this manifest:

![D33E886E-F79E-483E-A561-F949F7B5A8FB](https://user-images.githubusercontent.com/46350465/147838527-bfaac8c1-faf8-412e-ab6f-d01e566a6614.jpeg)

**Comment by caiosweet** [comment]
If you look closely, this line ` "requirements": ["bs4==0.0.1"],` is different. :0)

**Comment by pilot1981** [comment]
Thanks: this workaround worked fine!
